In [2]:
import numpy as np

In [1]:
#Creating First Matrix

In [5]:
mat1=np.arange(1,10)

In [6]:
mat1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
mat1=mat1.reshape(3,3)

In [8]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Creating Second Matrix

In [12]:
mat2=np.arange(12,30,2)

In [13]:
mat2

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
mat2=mat2.reshape(3,3)

In [19]:
mat2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

# Addition of Two Matrix

In [20]:
mat1+mat2

array([[13, 16, 19],
       [22, 25, 28],
       [31, 34, 37]])

In [21]:
mat3=mat1+mat2

In [22]:
mat3

array([[13, 16, 19],
       [22, 25, 28],
       [31, 34, 37]])

# Subtraction Of two matrix

In [23]:
mat1-mat2

array([[-11, -12, -13],
       [-14, -15, -16],
       [-17, -18, -19]])

In [24]:
mat3=mat1-mat2

In [25]:
mat3

array([[-11, -12, -13],
       [-14, -15, -16],
       [-17, -18, -19]])

# Multiplication of Matrix with scalar

In [26]:
mat4=mat1*3

In [27]:
mat4

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

# Division of Matrix with Scalar

In [28]:
mat1/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

# Multiplication of Two matrices

In [29]:
#first way

In [30]:
mat3=np.mat(mat1)*np.mat(mat2)

In [31]:
mat3

matrix([[120, 132, 144],
        [282, 312, 342],
        [444, 492, 540]])

In [32]:
#second way

In [37]:
mat3=np.dot(mat1,mat2)

In [38]:
mat3

array([[120, 132, 144],
       [282, 312, 342],
       [444, 492, 540]])

# Transpose OF Matrix

In [35]:
matT=mat1.T

In [36]:
matT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
a=np.matrix([2,3,4])

In [76]:
a=a.T

In [77]:
a.shape

(3, 1)

In [78]:
a

matrix([[2],
        [3],
        [4]])

# Dot Product or Inner Product

In [ ]:
#first Way

In [41]:
vector1=np.array([2,6,7])

In [42]:
vector2=np.array([34,12,9])

In [43]:
dotProduct=np.dot(vector1,vector2)

In [44]:
dotProduct

203

In [45]:
#second way

In [46]:
innerProduct=np.inner(vector1,vector2)

In [47]:
innerProduct

203

# Trace of Matrix

In [79]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
mat1Trace=mat1.trace()

In [81]:
mat1Trace

15

# Rank Of Matrix

In [82]:
#Given Matrix

In [83]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
#Rank

In [89]:
#linalg is used to find rank of matrix   

In [90]:
# np.linalg.matrix_rank(matrixName)   <-------Syntax

In [88]:
np.linalg.matrix_rank(mat1)

2

# Determinant Of Matrix

In [91]:
#Given Matrix

In [92]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
#Determinant    synntax   np.linalg.det(matrixName)

In [97]:
np.linalg.det(mat1)

0.0

# Inverse Of Matrix

In [101]:
mat3=np.matrix(((2,7,1),(45,78,2),(56,23,1)))

In [105]:
#Given Matrix

In [102]:
mat3

matrix([[ 2,  7,  1],
        [45, 78,  2],
        [56, 23,  1]])

In [106]:
#syntax np.linalg.inv(mattrixName)

In [103]:
mat3Inv=np.linalg.inv(mat3)

In [104]:
mat3Inv

matrix([[-0.01142857, -0.00571429,  0.02285714],
        [-0.02392857,  0.01928571, -0.01464286],
        [ 1.19035714, -0.12357143,  0.05678571]])

# Eigen Values And Eigen Vectors|

In [108]:
eigenvalue,eigenvector=np.linalg.eig(mat1)

In [109]:
eigenvalue

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [110]:
eigenvector

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])