In [2]:
import pandas as pd 
import numpy as np

In [3]:
data=pd.read_csv('Lending-company.csv',index_col='StringID')
df=data.copy()
df.head()

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_2       2  Product D         Female   Location 6  Region 6         NaN   
LoanID_3       3  Product B           Male   Location 8  Region 3     16600.0   
LoanID_4       4  Product A           Male  Location 26  Region 2     17600.0   
LoanID_5       5  Product B         Female  Location 34  Region 3     21250.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_2  02/01/2019     2200         45          365       3161       4096   
LoanID_3  08/12/2016     1000         45          365       2260       3205   
LoanID_4         NaN     2200         45          365       3141       4166   
LoanID_5  28/10/2017     2200         55          365       3570       4745   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_2       16041     Active  
LoanID_3       16340        NaN  
LoanID_4       16321     Active  
LoanID_5       14720     Active

# Gathering  Basic Information about Data

In [4]:
df.index

Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043],
           dtype='int64', name='LoanID', length=1043)

In [5]:
df.columns

Index(['StringID', 'Product', 'CustomerGender', 'Location', 'Region',
       'TotalPrice', 'StartDate', 'Deposit', 'DailyRate', 'TotalDaysYr',
       'AmtPaid36', 'AmtPaid60', 'AmtPaid360', 'LoanStatus'],
      dtype='object')

In [6]:
df.shape

(1043, 14)

In [7]:
df.axes

[Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
             ...
             1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043],
            dtype='int64', name='LoanID', length=1043),
 Index(['StringID', 'Product', 'CustomerGender', 'Location', 'Region',
        'TotalPrice', 'StartDate', 'Deposit', 'DailyRate', 'TotalDaysYr',
        'AmtPaid36', 'AmtPaid60', 'AmtPaid360', 'LoanStatus'],
       dtype='object')]

In [8]:
df.dtypes

StringID           object
Product            object
CustomerGender     object
Location           object
Region             object
TotalPrice        float64
StartDate          object
Deposit             int64
DailyRate           int64
TotalDaysYr         int64
AmtPaid36           int64
AmtPaid60           int64
AmtPaid360          int64
LoanStatus         object
dtype: object

In [10]:
df.values

array([['LoanID_1', 'Product B', 'Female', ..., 4166, 14621, 'Active'],
       ['LoanID_2', 'Product D', 'Female', ..., 4096, 16041, 'Active'],
       ['LoanID_3', 'Product B', 'Male', ..., 3205, 16340, nan],
       ...,
       ['LoanID_1041', 'Product A', 'NotSpecified', ..., 5143, 16617,
        'Finished Payment'],
       ['LoanID_1042', 'Product B', 'Female', ..., 3462, 15617,
        'Finished Payment'],
       ['LoanID_1043', 'Product A', 'NotSpecified', ..., 4743, 16617,
        'Finished Payment']], dtype=object)

In [12]:
df.head()

StringID    Product CustomerGender     Location    Region  TotalPrice  \
LoanID                                                                          
1       LoanID_1  Product B         Female   Location 3  Region 2     17600.0   
2       LoanID_2  Product D         Female   Location 6  Region 6         NaN   
3       LoanID_3  Product B           Male   Location 8  Region 3     16600.0   
4       LoanID_4  Product A           Male  Location 26  Region 2     17600.0   
5       LoanID_5  Product B         Female  Location 34  Region 3     21250.0   

         StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
LoanID                                                                      
1       04/07/2018     2200         45          365       3221       4166   
2       02/01/2019     2200         45          365       3161       4096   
3       08/12/2016     1000         45          365       2260       3205   
4              NaN     2200         45          365       3141       4166   
5       28/10/2017     2200         55          365       3570       4745   

        AmtPaid360 LoanStatus  
LoanID                         
1            14621     Active  
2            16041     Active  
3            16340        NaN  
4            16321     Active  
5            14720     Active

In [13]:
df.Product

LoanID
1       Product B
2       Product D
3       Product B
4       Product A
5       Product B
          ...    
1039    Product B
1040    Product A
1041    Product A
1042    Product B
1043    Product A
Name: Product, Length: 1043, dtype: object

In [14]:
df['Product']

LoanID
1       Product B
2       Product D
3       Product B
4       Product A
5       Product B
          ...    
1039    Product B
1040    Product A
1041    Product A
1042    Product B
1043    Product A
Name: Product, Length: 1043, dtype: object

In [15]:
df['Location']

LoanID
1        Location 3
2        Location 6
3        Location 8
4       Location 26
5       Location 34
           ...     
1039    Location 73
1040    Location 82
1041    Location 11
1042    Location 26
1043    Location 94
Name: Location, Length: 1043, dtype: object

In [20]:
c=['Location','Product']

In [22]:
df[c].head()

Location    Product
LoanID                        
1        Location 3  Product B
2        Location 6  Product D
3        Location 8  Product B
4       Location 26  Product A
5       Location 34  Product B

In [29]:
df.iloc[0]

StringID            LoanID_1
Product            Product B
CustomerGender        Female
Location          Location 3
Region              Region 2
TotalPrice           17600.0
StartDate         04/07/2018
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3221
AmtPaid60               4166
AmtPaid360             14621
LoanStatus            Active
Name: 1, dtype: object

In [30]:
df.iloc[2,6]

'08/12/2016'

In [31]:
df

StringID    Product CustomerGender     Location    Region  \
LoanID                                                                 
1          LoanID_1  Product B         Female   Location 3  Region 2   
2          LoanID_2  Product D         Female   Location 6  Region 6   
3          LoanID_3  Product B           Male   Location 8  Region 3   
4          LoanID_4  Product A           Male  Location 26  Region 2   
5          LoanID_5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
1039    LoanID_1039  Product B           Male  Location 73  Region 6   
1040    LoanID_1040  Product A           Male  Location 82  Region 1   
1041    LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1042    LoanID_1042  Product B         Female  Location 26  Region 6   
1043    LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

        TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
LoanID                                                                       
1          17600.0  04/07/2018     2200         45          365       3221   
2              NaN  02/01/2019     2200         45          365       3161   
3          16600.0  08/12/2016     1000         45          365       2260   
4          17600.0         NaN     2200         45          365       3141   
5          21250.0  28/10/2017     2200         55          365       3570   
...            ...         ...      ...        ...          ...        ...   
1039       17300.0  29/12/2018     2200         45          365       3251   
1040           NaN  28/03/2018     2200         45          365       4090   
1041       17300.0  26/04/2018     2200         45          365       4051   
1042       16300.0  25/10/2016     1000         45          365       1930   
1043       17300.0  15/05/2019     2200         45          365       4451   

        AmtPaid60  AmtPaid360        LoanStatus  
LoanID                                           
1            4166       14621            Active  
2            4096       16041            Active  
3            3205       16340               NaN  
4            4166       16321            Active  
5            4745       14720            Active  
...           ...         ...               ...  
1039         4743       16617  Finished Payment  
1040         5582       16617  Finished Payment  
1041         5143       16617  Finished Payment  
1042         3462       15617  Finished Payment  
1043         4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [33]:
df.iloc[1,:]

StringID            LoanID_2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: 2, dtype: object

In [36]:
df.iloc[:,3]

LoanID
1        Location 3
2        Location 6
3        Location 8
4       Location 26
5       Location 34
           ...     
1039    Location 73
1040    Location 82
1041    Location 11
1042    Location 26
1043    Location 94
Name: Location, Length: 1043, dtype: object

In [40]:
df.loc['LoanID_3']

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [41]:
df.loc[['LoanID_3'],['Product']]

Product
StringID           
LoanID_3  Product B

In [4]:
data=pd.read_csv('Lending-company.csv',index_col='LoanID')
df=data.copy()
df.head()

StringID    Product CustomerGender     Location    Region  TotalPrice  \
LoanID                                                                          
1       LoanID_1  Product B         Female   Location 3  Region 2     17600.0   
2       LoanID_2  Product D         Female   Location 6  Region 6         NaN   
3       LoanID_3  Product B           Male   Location 8  Region 3     16600.0   
4       LoanID_4  Product A           Male  Location 26  Region 2     17600.0   
5       LoanID_5  Product B         Female  Location 34  Region 3     21250.0   

         StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
LoanID                                                                      
1       04/07/2018     2200         45          365       3221       4166   
2       02/01/2019     2200         45          365       3161       4096   
3       08/12/2016     1000         45          365       2260       3205   
4              NaN     2200         45          365       3141       4166   
5       28/10/2017     2200         55          365       3570       4745   

        AmtPaid360 LoanStatus  
LoanID                         
1            14621     Active  
2            16041     Active  
3            16340        NaN  
4            16321     Active  
5            14720     Active

In [43]:
df.shape

(1043, 14)

In [50]:
df.iloc[1042]

StringID               LoanID_1043
Product                  Product A
CustomerGender        NotSpecified
Location               Location 94
Region                    Region 6
TotalPrice                 17300.0
StartDate               15/05/2019
Deposit                       2200
DailyRate                       45
TotalDaysYr                    365
AmtPaid36                     4451
AmtPaid60                     4743
AmtPaid360                   16617
LoanStatus        Finished Payment
Name: 1043, dtype: object

In [48]:
df.iloc[:,13]

LoanID
1                 Active
2                 Active
3                    NaN
4                 Active
5                 Active
              ...       
1039    Finished Payment
1040    Finished Payment
1041    Finished Payment
1042    Finished Payment
1043    Finished Payment
Name: LoanStatus, Length: 1043, dtype: object

In [54]:
df['TotalPrice'][1]

17600.0

In [6]:
df.head()

StringID    Product CustomerGender     Location    Region  TotalPrice  \
LoanID                                                                          
1       LoanID_1  Product B         Female   Location 3  Region 2     17600.0   
2       LoanID_2  Product D         Female   Location 6  Region 6         NaN   
3       LoanID_3  Product B           Male   Location 8  Region 3     16600.0   
4       LoanID_4  Product A           Male  Location 26  Region 2     17600.0   
5       LoanID_5  Product B         Female  Location 34  Region 3     21250.0   

         StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
LoanID                                                                      
1       04/07/2018     2200         45          365       3221       4166   
2       02/01/2019     2200         45          365       3161       4096   
3       08/12/2016     1000         45          365       2260       3205   
4              NaN     2200         45          365       3141       4166   
5       28/10/2017     2200         55          365       3570       4745   

        AmtPaid360 LoanStatus  
LoanID                         
1            14621     Active  
2            16041     Active  
3            16340        NaN  
4            16321     Active  
5            14720     Active

In [7]:
import numpy as np

In [8]:
mat=np.arange(1,10)

In [9]:
mat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
mat=mat.reshape(3,3)

In [15]:
np.ptp(mat)

8

In [16]:
np.ptp(mat,axis=0)

array([6, 6, 6])

In [17]:
np.ptp(mat,axis=1)

array([2, 2, 2])

In [18]:
np.percentile(mat,70)

6.6

In [19]:
np.var(mat)

6.666666666666667

In [20]:
np.var(mat,axis=0)

array([6., 6., 6.])

In [21]:
np.var(mat,axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [22]:
np.std(mat)

2.581988897471611